import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Matt Tierney | Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} max-w-6xl mx-auto px-4 bg-gradient-to-r from-slate-950/95 to-slate-900/95 selection:bg-sky-300 selection:text-slate-900`}
      >
        {children}
      </body>
    </html>
  );
}
